/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CreateSetupUrlRequest {
    organizationId?: string;
    canManageSaml?: boolean;
    canManageScim?: boolean;
}
