/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SSOReady from "../index";

export interface CreateOrganizationResponse {
    organization?: SSOReady.Organization;
}
