/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetSamlRedirectUrlResponse {
    /** Redirect your user to this URL to initiate the SAML login. */
    redirectUrl?: string;
}
