/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export interface GoogleProtobufAny {
    /** The type of the serialized message. */
    type?: string;
}
