/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SSOReady from "../index";

export interface ListScimDirectoriesResponse {
    scimDirectories?: SSOReady.ScimDirectory[];
    nextPageToken?: string;
}
