/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Organization {
    id?: string;
    environmentId?: string;
    externalId?: string;
    domains?: string[];
}
