/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RedeemSamlAccessCodeResponse {
    email?: string;
    state?: string;
    attributes?: Record<string, string>;
    organizationId?: string;
    organizationExternalId?: string;
    samlFlowId?: string;
}
