/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details about a user that just completed a SAML login.
 */
export interface RedeemSamlAccessCodeResponse {
    /** The user's email. */
    email?: string;
    /** Arbitrary data included in the corresponding GetSAMLRedirectURL request. */
    state?: string;
    /** Key-value attributes included by the identity provider. */
    attributes?: Record<string, string>;
    /** The organization this user belongs to. */
    organizationId?: string;
    /** The external ID of the organization this user belongs to. */
    organizationExternalId?: string;
    /** The SAML flow tracking this SAML login. */
    samlFlowId?: string;
}
