/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SamlConnection {
    id?: string;
    organizationId?: string;
    primary?: boolean;
    idpRedirectUrl?: string;
    idpCertificate?: string;
    idpEntityId?: string;
    spEntityId?: string;
    spAcsUrl?: string;
}
