/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScimDirectory {
    id?: string;
    organizationId?: string;
    primary?: boolean;
    scimBaseUrl?: string;
    clientBearerToken?: string;
    hasClientBearerToken?: boolean;
}
