/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScimUser {
    id?: string;
    scimDirectoryId?: string;
    email?: string;
    deleted?: boolean;
    attributes?: Record<string, unknown>;
}
