/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScimGroup {
    id?: string;
    scimDirectoryId?: string;
    displayName?: string;
    deleted?: boolean;
    attributes?: Record<string, unknown>;
}
