/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         organizationExternalId: "my_custom_external_id"
 *     }
 */
export interface ScimListScimGroupsRequest {
    scimDirectoryId?: string;
    organizationId?: string;
    organizationExternalId?: string;
    pageToken?: string;
}
