/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";

export const CreateSetupUrlResponse: core.serialization.ObjectSchema<
    serializers.CreateSetupUrlResponse.Raw,
    SSOReady.CreateSetupUrlResponse
> = core.serialization.object({
    url: core.serialization.string().optional(),
});

export declare namespace CreateSetupUrlResponse {
    interface Raw {
        url?: string | null;
    }
}
