/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";
import { ScimDirectory } from "./ScimDirectory";

export const CreateScimDirectoryResponse: core.serialization.ObjectSchema<
    serializers.CreateScimDirectoryResponse.Raw,
    SSOReady.CreateScimDirectoryResponse
> = core.serialization.object({
    scimDirectory: ScimDirectory.optional(),
});

export declare namespace CreateScimDirectoryResponse {
    interface Raw {
        scimDirectory?: ScimDirectory.Raw | null;
    }
}
