/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";
import { ScimGroup } from "./ScimGroup";

export const GetScimGroupResponse: core.serialization.ObjectSchema<
    serializers.GetScimGroupResponse.Raw,
    SSOReady.GetScimGroupResponse
> = core.serialization.object({
    scimGroup: ScimGroup.optional(),
});

export declare namespace GetScimGroupResponse {
    interface Raw {
        scimGroup?: ScimGroup.Raw | null;
    }
}
