/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";
import { ScimDirectory } from "./ScimDirectory";

export const ListScimDirectoriesResponse: core.serialization.ObjectSchema<
    serializers.ListScimDirectoriesResponse.Raw,
    SSOReady.ListScimDirectoriesResponse
> = core.serialization.object({
    scimDirectories: core.serialization.list(ScimDirectory).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListScimDirectoriesResponse {
    interface Raw {
        scimDirectories?: ScimDirectory.Raw[] | null;
        nextPageToken?: string | null;
    }
}
