/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";
import { ScimUser } from "./ScimUser";

export const ListScimUsersResponse: core.serialization.ObjectSchema<
    serializers.ListScimUsersResponse.Raw,
    SSOReady.ListScimUsersResponse
> = core.serialization.object({
    scimUsers: core.serialization.list(ScimUser).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListScimUsersResponse {
    interface Raw {
        scimUsers?: ScimUser.Raw[] | null;
        nextPageToken?: string | null;
    }
}
