/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";
import { ScimGroup } from "./ScimGroup";

export const ListScimGroupsResponse: core.serialization.ObjectSchema<
    serializers.ListScimGroupsResponse.Raw,
    SSOReady.ListScimGroupsResponse
> = core.serialization.object({
    scimGroups: core.serialization.list(ScimGroup).optional(),
    nextPageToken: core.serialization.string().optional(),
});

export declare namespace ListScimGroupsResponse {
    interface Raw {
        scimGroups?: ScimGroup.Raw[] | null;
        nextPageToken?: string | null;
    }
}
