/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";

export const Organization: core.serialization.ObjectSchema<serializers.Organization.Raw, SSOReady.Organization> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        environmentId: core.serialization.string().optional(),
        externalId: core.serialization.string().optional(),
        domains: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace Organization {
    interface Raw {
        id?: string | null;
        environmentId?: string | null;
        externalId?: string | null;
        domains?: string[] | null;
    }
}
