/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";

export const RedeemSamlAccessCodeResponse: core.serialization.ObjectSchema<
    serializers.RedeemSamlAccessCodeResponse.Raw,
    SSOReady.RedeemSamlAccessCodeResponse
> = core.serialization.object({
    email: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
    attributes: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    organizationId: core.serialization.string().optional(),
    organizationExternalId: core.serialization.string().optional(),
    samlFlowId: core.serialization.string().optional(),
});

export declare namespace RedeemSamlAccessCodeResponse {
    interface Raw {
        email?: string | null;
        state?: string | null;
        attributes?: Record<string, string> | null;
        organizationId?: string | null;
        organizationExternalId?: string | null;
        samlFlowId?: string | null;
    }
}
