/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";

export const RotateScimDirectoryBearerTokenResponse: core.serialization.ObjectSchema<
    serializers.RotateScimDirectoryBearerTokenResponse.Raw,
    SSOReady.RotateScimDirectoryBearerTokenResponse
> = core.serialization.object({
    bearerToken: core.serialization.string().optional(),
});

export declare namespace RotateScimDirectoryBearerTokenResponse {
    interface Raw {
        bearerToken?: string | null;
    }
}
