/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";

export const SamlConnection: core.serialization.ObjectSchema<serializers.SamlConnection.Raw, SSOReady.SamlConnection> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        organizationId: core.serialization.string().optional(),
        primary: core.serialization.boolean().optional(),
        idpRedirectUrl: core.serialization.string().optional(),
        idpCertificate: core.serialization.string().optional(),
        idpEntityId: core.serialization.string().optional(),
        spEntityId: core.serialization.string().optional(),
        spAcsUrl: core.serialization.string().optional(),
    });

export declare namespace SamlConnection {
    interface Raw {
        id?: string | null;
        organizationId?: string | null;
        primary?: boolean | null;
        idpRedirectUrl?: string | null;
        idpCertificate?: string | null;
        idpEntityId?: string | null;
        spEntityId?: string | null;
        spAcsUrl?: string | null;
    }
}
