/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";

export const ScimDirectory: core.serialization.ObjectSchema<serializers.ScimDirectory.Raw, SSOReady.ScimDirectory> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        organizationId: core.serialization.string().optional(),
        primary: core.serialization.boolean().optional(),
        scimBaseUrl: core.serialization.string().optional(),
        clientBearerToken: core.serialization.string().optional(),
        hasClientBearerToken: core.serialization.boolean().optional(),
    });

export declare namespace ScimDirectory {
    interface Raw {
        id?: string | null;
        organizationId?: string | null;
        primary?: boolean | null;
        scimBaseUrl?: string | null;
        clientBearerToken?: string | null;
        hasClientBearerToken?: boolean | null;
    }
}
