/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as SSOReady from "../../api/index";
import * as core from "../../core";
import { GoogleProtobufAny } from "./GoogleProtobufAny";

export const Status: core.serialization.ObjectSchema<serializers.Status.Raw, SSOReady.Status> =
    core.serialization.object({
        code: core.serialization.number().optional(),
        message: core.serialization.string().optional(),
        details: core.serialization.list(GoogleProtobufAny).optional(),
    });

export declare namespace Status {
    interface Raw {
        code?: number | null;
        message?: string | null;
        details?: GoogleProtobufAny.Raw[] | null;
    }
}
