/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as SSOReady from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const CreateSetupUrlRequest: core.serialization.Schema<
    serializers.management.CreateSetupUrlRequest.Raw,
    SSOReady.management.CreateSetupUrlRequest
> = core.serialization.object({
    organizationId: core.serialization.string().optional(),
    canManageSaml: core.serialization.boolean().optional(),
    canManageScim: core.serialization.boolean().optional(),
});

export declare namespace CreateSetupUrlRequest {
    interface Raw {
        organizationId?: string | null;
        canManageSaml?: boolean | null;
        canManageScim?: boolean | null;
    }
}
