/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Management } from "./api/resources/management/client/Client";
import { Saml } from "./api/resources/saml/client/Client";
import { Scim } from "./api/resources/scim/client/Client";

export declare namespace SSOReadyClient {
    interface Options {
        environment?: core.Supplier<environments.SSOReadyEnvironment | string>;
        apiKey?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class SSOReadyClient {
    constructor(protected readonly _options: SSOReadyClient.Options = {}) {}

    protected _management: Management | undefined;

    public get management(): Management {
        return (this._management ??= new Management(this._options));
    }

    protected _saml: Saml | undefined;

    public get saml(): Saml {
        return (this._saml ??= new Saml(this._options));
    }

    protected _scim: Scim | undefined;

    public get scim(): Scim {
        return (this._scim ??= new Scim(this._options));
    }
}
