/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SSOReadyEnvironment = {
    Default: "https://api.dev-ucarion.ssoready-nonprod.com",
} as const;

export type SSOReadyEnvironment = typeof SSOReadyEnvironment.Default;
