/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         samlConnectionId: "saml_conn_ac3bzzoqhaa88ozk29hhv12l",
 *         organizationId: "org_7cu5hsy9vrbi5d2k1qvbh19lj"
 *     }
 */
export interface GetSamlRedirectUrlRequest {
    /** The SAML connection to log in with. */
    samlConnectionId?: string;
    /**
     * The organization to log in with, identified by ID.
     * This will use the organization's primary SAML connection.
     *
     */
    organizationId?: string;
    /**
     * The organization to log in with, identified by external ID.
     * This will use the organization's primary SAML connection.
     *
     */
    organizationExternalId?: string;
    /**
     * An arbitrary string that will be returned back in the SAML
     * login's corresponding RedeemSAMLAccessCode call.
     *
     */
    state?: string;
}
