/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         samlAccessCode: "saml_access_code_94d90b43a2027a9084bfc792"
 *     }
 */
export interface RedeemSamlAccessCodeRequest {
    samlAccessCode?: string;
}
