/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as SSOReady from "../../../../../api/index";
import * as core from "../../../../../core";

export const GetSamlRedirectUrlRequest: core.serialization.Schema<
    serializers.GetSamlRedirectUrlRequest.Raw,
    SSOReady.GetSamlRedirectUrlRequest
> = core.serialization.object({
    samlConnectionId: core.serialization.string().optional(),
    organizationId: core.serialization.string().optional(),
    organizationExternalId: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
});

export declare namespace GetSamlRedirectUrlRequest {
    interface Raw {
        samlConnectionId?: string | null;
        organizationId?: string | null;
        organizationExternalId?: string | null;
        state?: string | null;
    }
}
