/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as SSOReady from "../../../../../api/index";
import * as core from "../../../../../core";

export const RedeemSamlAccessCodeRequest: core.serialization.Schema<
    serializers.RedeemSamlAccessCodeRequest.Raw,
    SSOReady.RedeemSamlAccessCodeRequest
> = core.serialization.object({
    samlAccessCode: core.serialization.string().optional(),
});

export declare namespace RedeemSamlAccessCodeRequest {
    interface Raw {
        samlAccessCode?: string | null;
    }
}
